import type { Metadata } from "next";
import { Syncopate, Montserrat } from "next/font/google";
import { Providers } from "@/components/Providers";
import { site } from "@/lib/site";
import "./globals.css";

// Headings & headlines — Syncopate (uppercase, geometric luxury)
const display = Syncopate({
    subsets: ["latin"],
    variable: "--font-display",
    display: "swap",
    weight: ["400", "700"],
});

// Body, specs, prices, compliance — Montserrat
const sans = Montserrat({
    subsets: ["latin"],
    variable: "--font-sans",
    display: "swap",
    weight: ["300", "400", "500", "600", "700"],
});

const siteUrl = "https://rovapeptides.com";
const title = "RovaPeptides — Research-Grade Peptides, Verified to the Batch";
const description =
    "Premium research peptides with 99%+ verified purity, USA laboratory batch testing, and third-party Certificates of Analysis on every batch. For Research Use Only.";

// Favicon + Apple touch icon are generated by app/icon.tsx and app/apple-icon.tsx
// (Next.js metadata file convention — picked up automatically, no manual <link> needed).
// OG/Twitter share image is generated by app/opengraph-image.tsx (Next.js auto-injects
// og:image / twitter:image so links shared on iMessage, WhatsApp, Twitter, etc. show a
// high-res brand card instead of a blank box).
export const metadata: Metadata = {
    metadataBase: new URL(siteUrl),
    title,
    description,
    openGraph: {
          title,
          description,
          url: siteUrl,
          siteName: site.name,
          type: "website",
          locale: "en_US",
    },
    twitter: {
          card: "summary_large_image",
          title,
          description,
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
          <html lang="en" className={`${display.variable} ${sans.variable}`}>
                  <body id="top">
                          <Providers>{children}</Providers>
                  </body>
          </html>
        );
}
